"""
@file_name: decision_schema.py
@author: NetMind.AI
@date: 2025-12-15
@description: Narrative intelligent decision-related Schema (Approach 2 design)

This file defines data structures related to Narrative intelligent decision-making
for Module Instances.
Core functionality:
1. ExecutionPath - Execution path enum (AGENT_LOOP vs DIRECT_TRIGGER)
2. PathExecutionResult - Unified result structure for execution paths
3. ContextStrategy - Context organization strategy (future extension)
4. DirectTriggerConfig - Direct trigger call configuration (future extension)
5. NarrativeDecision - Decision result (future extension)
"""

from enum import Enum
from typing import List, Optional, Any, Dict, TYPE_CHECKING
from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from xyz_agent_context.schema.context_schema import ContextData


class ExecutionPath(Enum):
    """
    Execution path type (Approach 2 core enum)

    Used after Step 2 intelligent decision to determine which execution path to follow:
    - AGENT_LOOP: Go through Context organization + Agent Loop (complex tasks requiring LLM reasoning)
    - DIRECT_TRIGGER: Directly call Module's Trigger (simple tasks with clear intent)
    """
    AGENT_LOOP = "agent_loop"           # CASE1: Go through Agent Loop (complex tasks)
    DIRECT_TRIGGER = "direct_trigger"   # CASE2: Directly call Trigger (simple tasks)


class DirectTriggerConfig(BaseModel):
    """
    Configuration for DIRECT_TRIGGER mode

    Used to directly call a Module's Trigger, skipping the Agent Loop.
    """
    module_class: str = Field(default="", description="Module class name to call")
    trigger_name: str = Field(default="", description="Trigger name")
    params: str = Field(default="{}", description="Parameters as JSON string")


class ModuleLoadResult(BaseModel):
    """
    Module load result (Instance level, containing module instances and execution path decision)

    Returned by ModuleService.load_modules(), containing:
    1. active_instances: Module Instance list (with bound module objects)
    2. execution_type: Execution path decision
    3. changes_summary: Instance change summary
    4. direct_trigger: DIRECT_TRIGGER mode configuration

    This design ensures that Step 2's output includes decision information,
    allowing Step 3 to select the execution path based on execution_type.

    Important changes:
    - Each ModuleInstance in active_instances has a bound module object (instance.module)
    - Removed module_objects (deprecated, use instance.module instead)
    - Removed module_list (deprecated)
    """

    # ===== Instance Information =====
    # active_instances list (each instance has a bound module object)
    active_instances: List[Any] = Field(
        default_factory=list,
        description="List of active Module Instances (with bound module objects)"
    )

    # ===== Change Information (for logging and debugging) =====
    changes_summary: Dict[str, List[str]] = Field(
        default_factory=lambda: {
            "added": [],
            "removed": [],
            "updated": [],
            "kept": []
        },
        description="Instance change summary"
    )

    changes_explanation: Dict[str, Any] = Field(
        default_factory=dict,
        description="Reasoning for each instance change (JSON structure output by LLM)"
    )

    # ===== Decision Reasoning =====
    decision_reasoning: str = Field(
        default="",
        description="LLM's overall decision reasoning (explains why these instances and execution path were chosen)"
    )

    # ===== Execution Path =====
    execution_type: "ExecutionPath" = Field(
        default=None,
        description="Execution path decision (AGENT_LOOP or DIRECT_TRIGGER)"
    )

    # ===== DIRECT_TRIGGER Information =====
    direct_trigger: Optional[DirectTriggerConfig] = Field(
        default=None,
        description="DIRECT_TRIGGER configuration (module_class, trigger_name, params)"
    )

    # ===== Module Relationship Graph =====
    relationship_graph: str = Field(
        default="",
        description="Module relationship graph (Mermaid graph TD format, generated by LLM)"
    )

    # ===== Complex Job Support =====
    key_to_id: Dict[str, str] = Field(
        default_factory=dict,
        description="task_key -> instance_id mapping (for Job creation)"
    )

    raw_instances: List[Any] = Field(
        default_factory=list,
        description="Raw InstanceDict list (containing job_config, for creating Jobs)"
    )

    class Config:
        arbitrary_types_allowed = True  # Allow arbitrary types (Module instances)


class PathExecutionResult(BaseModel):
    """
    Unified result structure for execution paths (shared by AGENT_LOOP and DIRECT_TRIGGER)

    Ensures both execution paths provide the intermediate information needed for Steps 7-8,
    allowing subsequent steps (Event update, Narrative association, Hook execution) to work uniformly.

    Step 7 needs:
        - final_output: Update Event
        - execution_steps: Generate event_log_entries

    Step 8 needs:
        - final_output: Hook parameters
        - agent_loop_response: Hook parameters (trace)
        - ctx_data: Hook parameters
    """

    # ========== Core Output ==========
    # Final output content (for Event update and Hook)
    final_output: str = Field(
        default="",
        description="Final output content of the execution"
    )

    # ========== Execution Tracking ==========
    # Execution step list (for generating event_log_entries)
    # AGENT_LOOP: From state.get_all_steps_as_list()
    # DIRECT_TRIGGER: From trigger execution step records
    execution_steps: List[dict] = Field(
        default_factory=list,
        description="List of steps during execution, for generating event_log_entries"
    )

    # Response count
    response_count: int = Field(
        default=0,
        description="Response count (AGENT_LOOP: number of Agent responses, DIRECT_TRIGGER: 1)"
    )

    # Agent Loop response list
    # AGENT_LOOP: Actual agent_loop_response
    # DIRECT_TRIGGER: Empty list
    agent_loop_response: List[Any] = Field(
        default_factory=list,
        description="Agent Loop response list (empty list for DIRECT_TRIGGER)"
    )

    # ========== Context Data ==========
    # Context data (for Hook)
    # AGENT_LOOP: From context.ctx_data (ContextData object)
    # DIRECT_TRIGGER: May be empty or contain trigger-related data
    ctx_data: Optional[Any] = Field(
        default=None,
        description="Context data (ContextData object), for Hook execution"
    )
