"""
@file_name: instance_schema.py
@author: NetMind.AI
@date: 2025-12-24
@description: ModuleInstance standalone data models

Includes:
- InstanceStatus - Instance status enum (migrated from module_schema)
- ModuleInstanceRecord - Instance database record model
- InstanceNarrativeLink - Association between Instance and Narrative
- ModuleInstance - Runtime Instance object (inherits ModuleInstanceRecord)

Design notes:
- ModuleInstanceRecord is the record persisted to the database
- ModuleInstance is the runtime object, with an added module field (not persisted)
- InstanceNarrativeLink manages the many-to-many relationship between Instance and Narrative
"""

from typing import Optional, Dict, Any, List, TYPE_CHECKING
from datetime import datetime
from enum import Enum
from pydantic import BaseModel, Field

if TYPE_CHECKING:
    from xyz_agent_context.module import XYZBaseModule


class InstanceStatus(Enum):
    """
    Module Instance status enum

    Used to identify the running state of an Instance
    """
    ACTIVE = "active"           # Active state, currently in use
    IN_PROGRESS = "in_progress" # In progress (primarily used by JobModule)
    BLOCKED = "blocked"         # Blocked state, waiting for dependencies to complete
    COMPLETED = "completed"     # Completed
    FAILED = "failed"           # Failed
    CANCELLED = "cancelled"     # Cancelled
    ARCHIVED = "archived"       # Archived


class LinkType(Enum):
    """
    Instance-Narrative association type enum
    """
    ACTIVE = "active"     # Currently active association
    HISTORY = "history"   # Historical association (Instance completed/removed)
    SHARED = "shared"     # Shared association (activated from another Narrative)


class ModuleInstanceRecord(BaseModel):
    """
    ModuleInstance database record

    This is the complete structure persisted to the module_instances table.

    Field descriptions:
    - instance_id: Unique identifier, format {prefix}_{uuid8}
    - module_class: Module class name, e.g., ChatModule, JobModule
    - agent_id: Owning Agent ID
    - user_id: Creator/associated user (optional, for User-level Instances)
    - is_public: Whether public (accessible by all users)

    Creation strategies:
    - Agent level: Auto-created when Agent is created, is_public=True, user_id=None
      e.g., AwarenessModule, SocialNetworkModule
    - User level: Created on first Agent + User interaction, is_public=False, user_id=xxx
      e.g., RAGModule, ChatModule
    - Task level: Created per task, is_public=False, user_id=xxx
      e.g., JobModule
    """
    # ===== Database Auto-increment ID =====
    id: Optional[int] = Field(default=None, description="Database auto-increment ID")

    # ===== Identity =====
    instance_id: str = Field(..., description="Unique identifier, format {prefix}_{uuid8}")
    module_class: str = Field(..., description="Module class name, e.g., ChatModule, JobModule")
    agent_id: str = Field(..., description="Owning Agent ID")

    # ===== Access Control =====
    user_id: Optional[str] = Field(default=None, description="Creator/associated user (optional)")
    is_public: bool = Field(default=False, description="Whether public (accessible by all users)")

    # ===== Status and Description =====
    status: InstanceStatus = Field(default=InstanceStatus.ACTIVE, description="Instance status")
    description: str = Field(default="", description="Responsibility description (generated by LLM)")

    # ===== Dependencies and Configuration =====
    dependencies: List[str] = Field(default_factory=list, description="Dependent instance_ids")
    config: Dict[str, Any] = Field(default_factory=dict, description="Configuration parameters")
    state: Optional[Dict[str, Any]] = Field(default=None, description="Runtime state")

    # ===== Retrieval Support =====
    routing_embedding: Optional[List[float]] = Field(default=None, description="1536-dimensional vector for semantic retrieval")
    keywords: List[str] = Field(default_factory=list, description="Keyword tags")
    topic_hint: str = Field(default="", description="Topic description/summary")

    # ===== Timestamps =====
    created_at: Optional[datetime] = Field(default=None, description="Creation time")
    last_used_at: Optional[datetime] = Field(default=None, description="Last used time")
    completed_at: Optional[datetime] = Field(default=None, description="Completion time")
    archived_at: Optional[datetime] = Field(default=None, description="Archive time")

    # ===== Poller Related Fields =====
    last_polled_status: Optional[str] = Field(
        default=None,
        description="Status at last poll (for detecting in_progress -> completed changes)"
    )
    callback_processed: bool = Field(
        default=False,
        description="Whether callback has been processed (prevents duplicate triggers)"
    )

    class Config:
        use_enum_values = True  # Use enum values during serialization


class ModuleInstance(ModuleInstanceRecord):
    """
    Runtime ModuleInstance

    Inherits from ModuleInstanceRecord, adding runtime fields.

    Differences from ModuleInstanceRecord:
    - Added module field: Actual Module object bound at runtime (not persisted)
    - Added linked_narrative_ids field: Associated Narrative IDs (loaded from links table at runtime)
    """
    # ===== Runtime Fields (not persisted) =====
    module: Optional["XYZBaseModule"] = Field(
        default=None,
        exclude=True,  # Not serialized to database
        description="Actual Module object bound at runtime"
    )
    linked_narrative_ids: List[str] = Field(
        default_factory=list,
        exclude=True,  # Not serialized to database
        description="Associated Narrative IDs (loaded from links table at runtime)"
    )

    class Config:
        use_enum_values = True
        arbitrary_types_allowed = True  # Allow arbitrary types (Module objects)


class InstanceNarrativeLink(BaseModel):
    """
    Association between Instance and Narrative

    Supports:
    - One Instance can be associated with multiple Narratives
    - One Narrative can have multiple Instances
    - Records association type and status

    Field descriptions:
    - link_type: Association type
      - active: Currently active association
      - history: Historical association (Instance completed/removed)
      - shared: Shared association (activated from another Narrative)
    - local_status: Status within this Narrative (may differ from Instance's global status)
    """
    # ===== Database Auto-increment ID =====
    id: Optional[int] = Field(default=None, description="Database auto-increment ID")

    instance_id: str = Field(..., description="Instance ID")
    narrative_id: str = Field(..., description="Narrative ID")

    # Association type
    link_type: LinkType = Field(default=LinkType.ACTIVE, description="Association type")

    # Status within this Narrative
    local_status: InstanceStatus = Field(
        default=InstanceStatus.ACTIVE,
        description="Status within this Narrative"
    )

    # Timestamps
    linked_at: Optional[datetime] = Field(default=None, description="Time association was established")
    unlinked_at: Optional[datetime] = Field(default=None, description="Time association was removed")

    class Config:
        use_enum_values = True


# ===== Helper Functions =====

def rebuild_module_instance_model():
    """
    Rebuild ModuleInstance model to resolve forward references

    Call this function after all modules have been imported
    """
    try:
        from xyz_agent_context.module import XYZBaseModule
        ModuleInstance.model_rebuild()
    except ImportError:
        # XYZBaseModule not yet defined, will be rebuilt later
        pass
